In [ ]:
!pip install catboost
!pip uninstall -y scikit-learn
!pip install scikit-learn==1.5.2
!pip uninstall -y xgboost
!pip install xgboost==2.1.3

Collecting catboost
  Downloading catboost-1.2.7-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.11/dist-packages (from catboost) (0.20.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<2.0,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from catboost) (1.26.4)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.11/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from catboost) (1.13.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.11/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24->catboost) (2025.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->catboost) (3.2.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly->catboost) (9.0.0)
Downloading catboost-1.2.7-cp311-cp311-manylinux2014_x86_64.whl (98.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 MB 5.3 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.7
Found existing installation: scikit-learn 1.6.1
Uninstalling scikit-learn-1.6.1:
  Successfully uninstalled scikit-learn-1.6.1
Collecting scikit-learn==1.5.2
  Downloading scikit_learn-1.5.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.5.2) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.5.2) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.5.2) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.5.2) (3.5.0)
Downloading scikit_learn-1.5.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 93.1 MB/s eta 0:00:00
Installing collected packages: scikit-learn
Successfully installed scikit-learn-1.5.2
Found existing installation: xgboost 2.1.4
Uninstalling xgboost-2.1.4:
  Successfully uninstalled xgboost-2.1.4
Collecting xgboost==2.1.3
  Downloading xgboost-2.1.3-py3-none-manylinux_2_28_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from xgboost==2.1.3) (1.26.4)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.11/dist-packages (from xgboost==2.1.3) (2.21.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from xgboost==2.1.3) (1.13.1)
Downloading xgboost-2.1.3-py3-none-manylinux_2_28_x86_64.whl (153.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.9/153.9 MB 6.2 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-2.1.3

In [40]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
import pandas as pd
import numpy as np

from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score

from imblearn.over_sampling import SMOTE
from sklearn.model_selection import KFold
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from xgboost.sklearn import XGBClassifier
import random

In [41]:
SEED = 42
np.random.seed(SEED)
random.seed(SEED)

**데이터 전처리**

In [42]:
train = pd.read_csv('./train.csv').drop(columns={'ID','방수','욕실수','제공플랫폼','매물확인방식','방향','주차가능여부','해당층','총층','전용면적','총주차대수'})
test = pd.read_csv('./test.csv').drop(columns={'ID','방수','욕실수','제공플랫폼','매물확인방식','방향','주차가능여부','해당층','총층','전용면적','총주차대수'})

In [43]:
train['게재일'] = pd.to_datetime(train['게재일'])

train['days_since_first_post'] = (train['게재일'] - train['게재일'].min()).dt.days

train['day_of_year'] = train['게재일'].dt.dayofyear

# 변환
train['cos_day'] = np.cos(2 * np.pi * train['day_of_year'] / 365)
train['sin_day'] = np.sin(2 * np.pi * train['day_of_year'] / 365)

test['게재일'] = pd.to_datetime(test['게재일'])

test['days_since_first_post'] = (test['게재일'] - train['게재일'].min()).dt.days

test['day_of_year'] = test['게재일'].dt.dayofyear

# 변환
test['cos_day'] = np.cos(2 * np.pi * test['day_of_year'] / 365)
test['sin_day'] = np.sin(2 * np.pi * test['day_of_year'] / 365)

train['관리비'] *= 10000
train = train[train['관리비'] <= 200000]
train.reset_index(drop=True,inplace=True)

test['관리비'] *= 10000

train.drop(columns={'게재일','day_of_year'},inplace=True)
test.drop(columns={'게재일','day_of_year'},inplace=True)

<ipython-input-43-1fbc182957d3>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.drop(columns={'게재일','day_of_year'},inplace=True)

In [ ]:
train['중개사무소'].value_counts()

중개사무소
G52Iz8V2B9    799
r82ax9M3U3     43
J52gJ2E4T6     32
H90uE4C0W5     30
b87Td0W4Y3     27
             ...
m75Dz8P6I7      1
A21Yr4B1U8      1
g11ci7P5V1      1
D26uW0Q2N3      1
L27JO3N6S2      1
Name: count, Length: 279, dtype: int64

**Frequency 인코딩**

In [44]:
agency_counts = train['중개사무소'].value_counts()

train['중개사무소_Count'] = train['중개사무소'].map(agency_counts)

test['중개사무소_Count'] = test['중개사무소'].apply(
    lambda x: agency_counts[x] if x in agency_counts else -1
)

train.drop(columns={'중개사무소'},inplace=True)
test.drop(columns={'중개사무소'},inplace=True)

In [45]:
X = train.drop(columns=['허위매물여부'])
y = train['허위매물여부']

In [46]:
X

,보증금,월세,관리비,days_since_first_post,cos_day,sin_day,중개사무소_Count
0,170500000.0,200000,0,608,0.997630,-0.068802,2
1,114000000.0,380000,0,580,0.852078,-0.523416,18
2,163500000.0,30000,100000,578,0.833556,-0.552435,797
3,346000000.0,530000,0,424,-0.995521,0.094537,19
4,153000000.0,530000,0,503,-0.300820,-0.953681,19
...,...,...,...,...,...,...,...
2430,159000000.0,550000,0,568,0.726608,-0.687053,16
2431,158500000.0,750000,20000,527,0.107381,-0.994218,11
2432,329000000.0,610000,100000,383,-0.696376,0.717677,797
2433,31000000.0,400000,80000,466,-0.809017,-0.587785,19
2434,126000000.0,340000,70000,330,0.141540,0.989932,21

**하이퍼파라미터 튜닝**

In [ ]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.1.0-py3-none-any.whl.metadata (16 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.14.0-py3-none-any.whl.metadata (7.4 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.37)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading Mako-1.3.8-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.1.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.11/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Downloading optuna-4.1.0-py3-none-any.whl (364 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 364.4/364.4 kB 21.9 MB/s eta 0:00:00
Downloading alembic-1.14.0-py3-none-any.whl (233 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.5/233.5 kB 16.0 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Downloading Mako-1.3.8-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB 5.9 MB/s eta 0:00:00
Installing collected packages: Mako, colorlog, alembic, optuna
Successfully installed Mako-1.3.8 alembic-1.14.0 colorlog-6.9.0 optuna-4.1.0

In [ ]:
import optuna

# 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,shuffle=True)

# SMOTE 적용
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

# XGBoost Optuna 최적화
def optimize_xgboost(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 820, 840),
        'max_depth': trial.suggest_int('max_depth', 11, 13),
        'learning_rate': trial.suggest_float('learning_rate', 0.2, 0.3),
        'subsample': trial.suggest_float('subsample', 0.5, 0.6),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.7, 0.8),
        'min_child_weight': trial.suggest_float('min_child_weight', 5, 6),
        'gamma': trial.suggest_float('gamma', 0, 1),
        'random_state': 42,
        'eval_metric': 'logloss'
    }
    model = XGBClassifier(**params)
    model.fit(X_train_smote, y_train_smote)
    y_pred = model.predict(X_test)
    return f1_score(y_test, y_pred, average='macro')

study_xgb = optuna.create_study(direction='maximize')
study_xgb.optimize(optimize_xgboost, n_trials=100)
print("Best parameters for XGBoost:", study_xgb.best_params)
print("Best Macro F1 Score for XGBoost:", study_xgb.best_value)

[I 2025-01-16 03:55:18,382] A new study created in memory with name: no-name-f1f65263-0f1b-4c20-a370-835a9f746ce9
[I 2025-01-16 03:55:19,469] Trial 0 finished with value: 0.8631664615891409 and parameters: {'n_estimators': 835, 'max_depth': 13, 'learning_rate': 0.28799344304368124, 'subsample': 0.5669466681438123, 'colsample_bytree': 0.7354274334658338, 'min_child_weight': 5.543153652146846, 'gamma': 0.6208529842686266}. Best is trial 0 with value: 0.8631664615891409.
[I 2025-01-16 03:55:20,332] Trial 1 finished with value: 0.8825657101519171 and parameters: {'n_estimators': 834, 'max_depth': 12, 'learning_rate': 0.2670393103293681, 'subsample': 0.5014795473949711, 'colsample_bytree': 0.7018162584804811, 'min_child_weight': 5.983888061042634, 'gamma': 0.7070709877502478}. Best is trial 1 with value: 0.8825657101519171.
[I 2025-01-16 03:55:21,245] Trial 2 finished with value: 0.8785766288683441 and parameters: {'n_estimators': 822, 'max_depth': 13, 'learning_rate': 0.21976177964344826, 'subsample': 0.5601383136812877, 'colsample_bytree': 0.7737342417460419, 'min_child_weight': 5.970855737858676, 'gamma': 0.775861944245337}. Best is trial 1 with value: 0.8825657101519171.
[I 2025-01-16 03:55:24,974] Trial 3 finished with value: 0.8882904985588767 and parameters: {'n_estimators': 837, 'max_depth': 12, 'learning_rate': 0.22055453831605257, 'subsample': 0.5590247805871498, 'colsample_bytree': 0.7633228018684023, 'min_child_weight': 5.811379147498737, 'gamma': 0.8785299424139117}. Best is trial 3 with value: 0.8882904985588767.
[I 2025-01-16 03:55:26,258] Trial 4 finished with value: 0.8923519009725907 and parameters: {'n_estimators': 822, 'max_depth': 13, 'learning_rate': 0.2041331333346391, 'subsample': 0.5128851902538463, 'colsample_bytree': 0.7815089632378885, 'min_child_weight': 5.179372785287327, 'gamma': 0.768867770015139}. Best is trial 4 with value: 0.8923519009725907.
[I 2025-01-16 03:55:26,693] Trial 5 finished with value: 0.8803381001523416 and parameters: {'n_estimators': 823, 'max_depth': 13, 'learning_rate': 0.23729842187809747, 'subsample': 0.59563453757428, 'colsample_bytree': 0.7551027221337638, 'min_child_weight': 5.768490733871596, 'gamma': 0.08111791322867601}. Best is trial 4 with value: 0.8923519009725907.
[I 2025-01-16 03:55:27,114] Trial 6 finished with value: 0.8825657101519171 and parameters: {'n_estimators': 834, 'max_depth': 13, 'learning_rate': 0.22019685465574212, 'subsample': 0.5099927914449476, 'colsample_bytree': 0.7804630857560328, 'min_child_weight': 5.093023847706368, 'gamma': 0.2521833031808707}. Best is trial 4 with value: 0.8923519009725907.
[I 2025-01-16 03:55:27,503] Trial 7 finished with value: 0.8726032573416139 and parameters: {'n_estimators': 829, 'max_depth': 11, 'learning_rate': 0.265089046831421, 'subsample': 0.5637370824110934, 'colsample_bytree': 0.7063226271895282, 'min_child_weight': 5.576885641906459, 'gamma': 0.42165654911603045}. Best is trial 4 with value: 0.8923519009725907.
[I 2025-01-16 03:55:27,864] Trial 8 finished with value: 0.8803381001523416 and parameters: {'n_estimators': 824, 'max_depth': 13, 'learning_rate': 0.25275158362567074, 'subsample': 0.5750814625477856, 'colsample_bytree': 0.7122945368269552, 'min_child_weight': 5.857528589520671, 'gamma': 0.6158054866021685}. Best is trial 4 with value: 0.8923519009725907.
[I 2025-01-16 03:55:28,220] Trial 9 finished with value: 0.8842863931569777 and parameters: {'n_estimators': 839, 'max_depth': 13, 'learning_rate': 0.29005234634246, 'subsample': 0.5787586488109788, 'colsample_bytree': 0.7970515498347994, 'min_child_weight': 5.548830878963634, 'gamma': 0.7185899364365939}. Best is trial 4 with value: 0.8923519009725907.
[I 2025-01-16 03:55:28,675] Trial 10 finished with value: 0.870765148164529 and parameters: {'n_estimators': 827, 'max_depth': 11, 'learning_rate': 0.2009812858512303, 'subsample': 0.5301644127892041, 'colsample_bytree': 0.7985371924062564, 'min_child_weight': 5.080212762483076, 'gamma': 0.44336260352820317}. Best is trial 4 with value: 0.8923519009725907.
[I 2025-01-16 03:55:29,047] Trial 11 finished with value: 0.870765148164529 and parameters: {'n_estimators': 839, 'max_depth': 12, 'learning_rate': 0.20186290081160332, 'subsample': 0.5348025202438298, 'colsample_bytree': 0.7598516625358029, 'min_child_weight': 5.315442107388104, 'gamma': 0.9912184097428496}. Best is trial 4 with value: 0.8923519009725907.
[I 2025-01-16 03:55:29,439] Trial 12 finished with value: 0.8726032573416139 and parameters: {'n_estimators': 820, 'max_depth': 12, 'learning_rate': 0.2223370179604911, 'subsample': 0.5400065840614521, 'colsample_bytree': 0.7766003156715385, 'min_child_weight': 5.326037709521618, 'gamma': 0.9810510914218206}. Best is trial 4 with value: 0.8923519009725907.
[I 2025-01-16 03:55:29,828] Trial 13 finished with value: 0.8964721364579643 and parameters: {'n_estimators': 831, 'max_depth': 12, 'learning_rate': 0.2344025458647505, 'subsample': 0.5188234845604454, 'colsample_bytree': 0.7406343037947305, 'min_child_weight': 5.293411905529485, 'gamma': 0.843692765546423}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:30,212] Trial 14 finished with value: 0.8825657101519171 and parameters: {'n_estimators': 831, 'max_depth': 11, 'learning_rate': 0.23846688461259624, 'subsample': 0.5168974077087535, 'colsample_bytree': 0.7339550216169055, 'min_child_weight': 5.263193823523379, 'gamma': 0.8459275815599036}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:30,641] Trial 15 finished with value: 0.8785766288683441 and parameters: {'n_estimators': 826, 'max_depth': 12, 'learning_rate': 0.24289262967344316, 'subsample': 0.5214925446672736, 'colsample_bytree': 0.7319569779538065, 'min_child_weight': 5.210259725283604, 'gamma': 0.5537058967424571}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:31,032] Trial 16 finished with value: 0.890718074255406 and parameters: {'n_estimators': 831, 'max_depth': 12, 'learning_rate': 0.20880340309482928, 'subsample': 0.5001146458478275, 'colsample_bytree': 0.7444996204838469, 'min_child_weight': 5.416187721208419, 'gamma': 0.8716347040741806}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:31,496] Trial 17 finished with value: 0.8825657101519171 and parameters: {'n_estimators': 827, 'max_depth': 11, 'learning_rate': 0.25503009958071343, 'subsample': 0.5239915667704982, 'colsample_bytree': 0.7453073047644163, 'min_child_weight': 5.031932671679067, 'gamma': 0.24640638317646368}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:31,880] Trial 18 finished with value: 0.8688627591778117 and parameters: {'n_estimators': 829, 'max_depth': 12, 'learning_rate': 0.22806391773393656, 'subsample': 0.5504253150696292, 'colsample_bytree': 0.7200128351968188, 'min_child_weight': 5.181900822988998, 'gamma': 0.7925728352682017}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:32,267] Trial 19 finished with value: 0.8785766288683441 and parameters: {'n_estimators': 820, 'max_depth': 13, 'learning_rate': 0.27621283242906003, 'subsample': 0.5454966890979785, 'colsample_bytree': 0.7848763102824654, 'min_child_weight': 5.408724908473525, 'gamma': 0.6576851866604916}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:32,713] Trial 20 finished with value: 0.8764441842310695 and parameters: {'n_estimators': 832, 'max_depth': 12, 'learning_rate': 0.21030730338547954, 'subsample': 0.5126133629238513, 'colsample_bytree': 0.7676681823692407, 'min_child_weight': 5.160280159137448, 'gamma': 0.5381204566042721}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:33,107] Trial 21 finished with value: 0.8825657101519171 and parameters: {'n_estimators': 832, 'max_depth': 12, 'learning_rate': 0.21074731764959423, 'subsample': 0.5020444397834767, 'colsample_bytree': 0.7480955386410032, 'min_child_weight': 5.4159478859825265, 'gamma': 0.9028332376985448}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:33,491] Trial 22 finished with value: 0.8764441842310695 and parameters: {'n_estimators': 830, 'max_depth': 12, 'learning_rate': 0.2094418424683893, 'subsample': 0.5084777572981141, 'colsample_bytree': 0.7416315939842139, 'min_child_weight': 5.4163328988087756, 'gamma': 0.9057365152264254}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:33,898] Trial 23 finished with value: 0.8842863931569777 and parameters: {'n_estimators': 825, 'max_depth': 12, 'learning_rate': 0.23078911498481347, 'subsample': 0.500019711513924, 'colsample_bytree': 0.7204506754672225, 'min_child_weight': 5.659949099305447, 'gamma': 0.7913677808133569}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:34,297] Trial 24 finished with value: 0.8882904985588767 and parameters: {'n_estimators': 828, 'max_depth': 12, 'learning_rate': 0.2112677298350129, 'subsample': 0.525358346034903, 'colsample_bytree': 0.725538958587923, 'min_child_weight': 5.352105063546984, 'gamma': 0.9411689593349305}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:34,720] Trial 25 finished with value: 0.8882904985588767 and parameters: {'n_estimators': 833, 'max_depth': 11, 'learning_rate': 0.20180558989458414, 'subsample': 0.5153608796601733, 'colsample_bytree': 0.7561977168704572, 'min_child_weight': 5.468522607968247, 'gamma': 0.8225622049513021}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:35,114] Trial 26 finished with value: 0.890718074255406 and parameters: {'n_estimators': 836, 'max_depth': 12, 'learning_rate': 0.22950778387177861, 'subsample': 0.5081392709755872, 'colsample_bytree': 0.7871936980342935, 'min_child_weight': 5.251577939649735, 'gamma': 0.7204672088469524}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:35,481] Trial 27 finished with value: 0.8803381001523416 and parameters: {'n_estimators': 831, 'max_depth': 13, 'learning_rate': 0.2473524758828118, 'subsample': 0.5322662768713204, 'colsample_bytree': 0.7398409461833559, 'min_child_weight': 5.666807999550003, 'gamma': 0.9997556274045969}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:35,926] Trial 28 finished with value: 0.8882904985588767 and parameters: {'n_estimators': 822, 'max_depth': 12, 'learning_rate': 0.21567601087068453, 'subsample': 0.5185104682028848, 'colsample_bytree': 0.7521945575272666, 'min_child_weight': 5.129660842490209, 'gamma': 0.8559606072159368}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:37,272] Trial 29 finished with value: 0.8785766288683441 and parameters: {'n_estimators': 836, 'max_depth': 13, 'learning_rate': 0.23562910727229455, 'subsample': 0.5049452749819063, 'colsample_bytree': 0.7687105687241835, 'min_child_weight': 5.0058495017219835, 'gamma': 0.6144396772353928}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:38,984] Trial 30 finished with value: 0.8948845240664796 and parameters: {'n_estimators': 830, 'max_depth': 13, 'learning_rate': 0.28258742046626484, 'subsample': 0.5401886273311012, 'colsample_bytree': 0.7282091936709969, 'min_child_weight': 5.267290560228753, 'gamma': 0.7424866715852615}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:40,122] Trial 31 finished with value: 0.8882904985588767 and parameters: {'n_estimators': 830, 'max_depth': 13, 'learning_rate': 0.2983614604202507, 'subsample': 0.539857162979118, 'colsample_bytree': 0.7292890641931985, 'min_child_weight': 5.277994720817933, 'gamma': 0.7615047900509629}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:40,507] Trial 32 finished with value: 0.8803381001523416 and parameters: {'n_estimators': 834, 'max_depth': 13, 'learning_rate': 0.2788820776725843, 'subsample': 0.5250162018572188, 'colsample_bytree': 0.7377124486840313, 'min_child_weight': 5.359445432744838, 'gamma': 0.6752562493823863}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:40,918] Trial 33 finished with value: 0.8688139767567151 and parameters: {'n_estimators': 828, 'max_depth': 13, 'learning_rate': 0.2642833835467756, 'subsample': 0.5493159183730844, 'colsample_bytree': 0.7462086987145929, 'min_child_weight': 5.220091525550369, 'gamma': 0.7454778952063373}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:41,297] Trial 34 finished with value: 0.8842863931569777 and parameters: {'n_estimators': 832, 'max_depth': 12, 'learning_rate': 0.2582884021859679, 'subsample': 0.5124940449085844, 'colsample_bytree': 0.7219969825159329, 'min_child_weight': 5.490145734761642, 'gamma': 0.9321639955572208}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:41,675] Trial 35 finished with value: 0.8803381001523416 and parameters: {'n_estimators': 825, 'max_depth': 13, 'learning_rate': 0.2820961377177377, 'subsample': 0.5290211907618727, 'colsample_bytree': 0.7128129171971852, 'min_child_weight': 5.299111265015662, 'gamma': 0.8305109155183605}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:42,089] Trial 36 finished with value: 0.8882904985588767 and parameters: {'n_estimators': 835, 'max_depth': 13, 'learning_rate': 0.2731091871110394, 'subsample': 0.5551371673341993, 'colsample_bytree': 0.7283942582456907, 'min_child_weight': 5.1289910160725745, 'gamma': 0.6803564456569507}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:42,565] Trial 37 finished with value: 0.8764441842310695 and parameters: {'n_estimators': 822, 'max_depth': 12, 'learning_rate': 0.22279518484587219, 'subsample': 0.5391765130538659, 'colsample_bytree': 0.7418197797264431, 'min_child_weight': 5.369517543481038, 'gamma': 0.002306279597542482}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:42,995] Trial 38 finished with value: 0.8764441842310695 and parameters: {'n_estimators': 833, 'max_depth': 13, 'learning_rate': 0.20630141172403768, 'subsample': 0.5050497256526841, 'colsample_bytree': 0.7002762345336185, 'min_child_weight': 5.074737945474847, 'gamma': 0.5862136552806839}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:43,378] Trial 39 finished with value: 0.8923519009725907 and parameters: {'n_estimators': 830, 'max_depth': 12, 'learning_rate': 0.21765402012403642, 'subsample': 0.5975580911477681, 'colsample_bytree': 0.7616629006647899, 'min_child_weight': 5.459512788121811, 'gamma': 0.8804028759982417}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:43,795] Trial 40 finished with value: 0.8785766288683441 and parameters: {'n_estimators': 829, 'max_depth': 13, 'learning_rate': 0.21665599802026025, 'subsample': 0.5953899369580106, 'colsample_bytree': 0.7921364560972599, 'min_child_weight': 5.612191533351255, 'gamma': 0.48625436001199973}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:44,213] Trial 41 finished with value: 0.8964721364579643 and parameters: {'n_estimators': 830, 'max_depth': 12, 'learning_rate': 0.21650553623825217, 'subsample': 0.5677594796970739, 'colsample_bytree': 0.7633693832967015, 'min_child_weight': 5.457419993601185, 'gamma': 0.8836459629590053}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:44,600] Trial 42 finished with value: 0.8842863931569777 and parameters: {'n_estimators': 830, 'max_depth': 12, 'learning_rate': 0.2252629892682762, 'subsample': 0.5729055069510822, 'colsample_bytree': 0.7625870022382957, 'min_child_weight': 5.520432637865955, 'gamma': 0.8027496236662457}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:44,999] Trial 43 finished with value: 0.8842863931569777 and parameters: {'n_estimators': 828, 'max_depth': 12, 'learning_rate': 0.21581990994166997, 'subsample': 0.5909906893414778, 'colsample_bytree': 0.7736985833297952, 'min_child_weight': 5.476909043928867, 'gamma': 0.9449887454118058}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:45,379] Trial 44 finished with value: 0.8803381001523416 and parameters: {'n_estimators': 838, 'max_depth': 12, 'learning_rate': 0.2335054027978724, 'subsample': 0.5818329851320968, 'colsample_bytree': 0.7578845704582738, 'min_child_weight': 5.230274286563698, 'gamma': 0.8812852429155552}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:45,771] Trial 45 finished with value: 0.8688139767567151 and parameters: {'n_estimators': 827, 'max_depth': 11, 'learning_rate': 0.24218429016475002, 'subsample': 0.5688979176944206, 'colsample_bytree': 0.7517791998553751, 'min_child_weight': 5.174681738816892, 'gamma': 0.7663472005392038}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:46,231] Trial 46 finished with value: 0.8764441842310695 and parameters: {'n_estimators': 823, 'max_depth': 12, 'learning_rate': 0.20455542014972178, 'subsample': 0.5831330352606542, 'colsample_bytree': 0.7690720427429723, 'min_child_weight': 5.93368747487016, 'gamma': 0.33804280190574015}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:46,649] Trial 47 finished with value: 0.8803381001523416 and parameters: {'n_estimators': 826, 'max_depth': 12, 'learning_rate': 0.21739202061958846, 'subsample': 0.5624652193958878, 'colsample_bytree': 0.7795885289066975, 'min_child_weight': 5.574121074866832, 'gamma': 0.7021351033162752}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:47,016] Trial 48 finished with value: 0.8848735263585252 and parameters: {'n_estimators': 829, 'max_depth': 13, 'learning_rate': 0.2940078934996687, 'subsample': 0.5889636030531266, 'colsample_bytree': 0.7634521504080305, 'min_child_weight': 5.315836783684563, 'gamma': 0.9496687064108826}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:47,416] Trial 49 finished with value: 0.8767525434023384 and parameters: {'n_estimators': 840, 'max_depth': 12, 'learning_rate': 0.22510273341401815, 'subsample': 0.5584300376853897, 'colsample_bytree': 0.7739855549658291, 'min_child_weight': 5.71722315679637, 'gamma': 0.8321758292080912}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:47,821] Trial 50 finished with value: 0.8842863931569777 and parameters: {'n_estimators': 831, 'max_depth': 12, 'learning_rate': 0.23992280501444774, 'subsample': 0.5678949355126998, 'colsample_bytree': 0.7150622627950658, 'min_child_weight': 5.438580505553185, 'gamma': 0.6410516752656631}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:48,240] Trial 51 finished with value: 0.8842863931569777 and parameters: {'n_estimators': 833, 'max_depth': 12, 'learning_rate': 0.20692476912036975, 'subsample': 0.521231576311665, 'colsample_bytree': 0.7355683095004754, 'min_child_weight': 5.371340352457151, 'gamma': 0.8654247214887959}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:48,618] Trial 52 finished with value: 0.8842863931569777 and parameters: {'n_estimators': 831, 'max_depth': 12, 'learning_rate': 0.212260651807731, 'subsample': 0.5993003823513012, 'colsample_bytree': 0.7445424237634397, 'min_child_weight': 5.4379120352071615, 'gamma': 0.9058382608781731}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:49,024] Trial 53 finished with value: 0.8764441842310695 and parameters: {'n_estimators': 830, 'max_depth': 12, 'learning_rate': 0.21439385181542892, 'subsample': 0.5352453547895368, 'colsample_bytree': 0.7512446319805436, 'min_child_weight': 5.531898033486359, 'gamma': 0.7454283630042529}. Best is trial 13 with value: 0.8964721364579643.
[I 2025-01-16 03:55:49,432] Trial 54 finished with value: 0.8803381001523416 and parameters: {'n_estimators': 832, 'max_depth': 12, 'learning_rate': 0.2188492457688091, 'subsample': 0.5444231986027747, 'colsample_bytree': 0.7619001291532361, 'min_child_weight': 5.387940624774322, 'gamma': 0.8576683356430788}. Best is trial 13 with value: 0.8964721364579643.

Best parameters for XGBoost: {'n_estimators': 832, 'max_depth': 12, 'learning_rate': 0.20593358762047578, 'subsample': 0.5075069759848869, 'colsample_bytree': 0.7424805892464985, 'min_child_weight': 5.409454498304978, 'gamma': 0.9114298633986331}
Best Macro F1 Score for XGBoost: 0.9006527947776417

In [ ]:
# LightGBM Optuna 최적화
def optimize_lightgbm(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 345, 355),
        'max_depth': trial.suggest_int('max_depth', 65, 67),
        'learning_rate': trial.suggest_float('learning_rate', 0.15, 0.17),
        'subsample': trial.suggest_float('subsample', 0.5, 0.6),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.7, 0.8),
        'min_child_samples': trial.suggest_int('min_child_samples', 5, 6),
        'num_leaves': trial.suggest_int('num_leaves', 27, 28),
        #'lambda_l1': trial.suggest_float('lambda_l1', 0.0, 10.0),
        #'lambda_l2': trial.suggest_float('lambda_l2', 0.0, 10.0),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.6, 0.7),
        'bagging_fraction': trial.suggest_float('bagging_fraction', 0.7, 0.8),
        'random_state': 42,
        'verbose': -1
    }
    model = LGBMClassifier(**params)
    model.fit(X_train_smote, y_train_smote)
    y_pred = model.predict(X_test)
    return f1_score(y_test, y_pred, average='macro')

study_lgb = optuna.create_study(direction='maximize')
study_lgb.optimize(optimize_lightgbm, n_trials=100)
print("Best parameters for LightGBM:", study_lgb.best_params)
print("Best Macro F1 Score for LightGBM:", study_lgb.best_value)

[I 2025-01-16 03:52:52,237] A new study created in memory with name: no-name-3d3528d5-6323-4cfd-b951-fa5214fa6798
[I 2025-01-16 03:52:53,030] Trial 0 finished with value: 0.8705873402312843 and parameters: {'n_estimators': 354, 'max_depth': 67, 'learning_rate': 0.16334304772766467, 'subsample': 0.5784738572523095, 'colsample_bytree': 0.7845045193801675, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6850891104321319, 'bagging_fraction': 0.7374090593525049}. Best is trial 0 with value: 0.8705873402312843.
[I 2025-01-16 03:52:53,772] Trial 1 finished with value: 0.8814589665653495 and parameters: {'n_estimators': 348, 'max_depth': 65, 'learning_rate': 0.15275538581127557, 'subsample': 0.5134430310390805, 'colsample_bytree': 0.7318824193992858, 'min_child_samples': 6, 'num_leaves': 27, 'feature_fraction': 0.6509501613267878, 'bagging_fraction': 0.7472805132964118}. Best is trial 1 with value: 0.8814589665653495.
[I 2025-01-16 03:52:54,536] Trial 2 finished with value: 0.8705873402312843 and parameters: {'n_estimators': 348, 'max_depth': 66, 'learning_rate': 0.16844758800689308, 'subsample': 0.5582684820374333, 'colsample_bytree': 0.7430595961991272, 'min_child_samples': 6, 'num_leaves': 27, 'feature_fraction': 0.6563315401092856, 'bagging_fraction': 0.7464826512490017}. Best is trial 1 with value: 0.8814589665653495.
[I 2025-01-16 03:52:55,268] Trial 3 finished with value: 0.874608026038979 and parameters: {'n_estimators': 347, 'max_depth': 65, 'learning_rate': 0.1652192888019598, 'subsample': 0.567533862693827, 'colsample_bytree': 0.7668292767921191, 'min_child_samples': 5, 'num_leaves': 27, 'feature_fraction': 0.6411975064283953, 'bagging_fraction': 0.7762695718997003}. Best is trial 1 with value: 0.8814589665653495.
[I 2025-01-16 03:52:55,809] Trial 4 finished with value: 0.8859154929577465 and parameters: {'n_estimators': 353, 'max_depth': 65, 'learning_rate': 0.16285276562976184, 'subsample': 0.5868395788239275, 'colsample_bytree': 0.752995248887911, 'min_child_samples': 5, 'num_leaves': 27, 'feature_fraction': 0.6657876459895017, 'bagging_fraction': 0.7845989738120729}. Best is trial 4 with value: 0.8859154929577465.
[I 2025-01-16 03:52:56,378] Trial 5 finished with value: 0.8968948891031823 and parameters: {'n_estimators': 354, 'max_depth': 66, 'learning_rate': 0.16046295070716587, 'subsample': 0.5444761397841665, 'colsample_bytree': 0.7507158826032321, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6156298541863398, 'bagging_fraction': 0.7914429492420647}. Best is trial 5 with value: 0.8968948891031823.
[I 2025-01-16 03:52:56,895] Trial 6 finished with value: 0.8781485053037608 and parameters: {'n_estimators': 349, 'max_depth': 67, 'learning_rate': 0.16255863382589422, 'subsample': 0.5699411370124068, 'colsample_bytree': 0.7311632970104734, 'min_child_samples': 5, 'num_leaves': 27, 'feature_fraction': 0.6484733704733054, 'bagging_fraction': 0.7968381442654524}. Best is trial 5 with value: 0.8968948891031823.
[I 2025-01-16 03:52:57,402] Trial 7 finished with value: 0.8781485053037608 and parameters: {'n_estimators': 351, 'max_depth': 66, 'learning_rate': 0.15377116882635863, 'subsample': 0.5697924774673412, 'colsample_bytree': 0.704632210385221, 'min_child_samples': 6, 'num_leaves': 27, 'feature_fraction': 0.6170859170154395, 'bagging_fraction': 0.7739368450049839}. Best is trial 5 with value: 0.8968948891031823.
[I 2025-01-16 03:52:57,955] Trial 8 finished with value: 0.8859154929577465 and parameters: {'n_estimators': 346, 'max_depth': 65, 'learning_rate': 0.1522412872259571, 'subsample': 0.5362133718434059, 'colsample_bytree': 0.7346611699120269, 'min_child_samples': 5, 'num_leaves': 27, 'feature_fraction': 0.6403402302361936, 'bagging_fraction': 0.7738876655279407}. Best is trial 5 with value: 0.8968948891031823.
[I 2025-01-16 03:52:58,480] Trial 9 finished with value: 0.9049295774647887 and parameters: {'n_estimators': 354, 'max_depth': 65, 'learning_rate': 0.16785948055373515, 'subsample': 0.5068100961322698, 'colsample_bytree': 0.7406603047617699, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6745085398715627, 'bagging_fraction': 0.7901979978913599}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:52:59,085] Trial 10 finished with value: 0.8705873402312843 and parameters: {'n_estimators': 351, 'max_depth': 65, 'learning_rate': 0.1694835280679021, 'subsample': 0.5025356506215872, 'colsample_bytree': 0.7077063503646901, 'min_child_samples': 6, 'num_leaves': 28, 'feature_fraction': 0.6994462939829718, 'bagging_fraction': 0.7034166756304917}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:52:59,808] Trial 11 finished with value: 0.8669014084507043 and parameters: {'n_estimators': 355, 'max_depth': 66, 'learning_rate': 0.15840794358590515, 'subsample': 0.5377644328138014, 'colsample_bytree': 0.7675753834067858, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6064979232686836, 'bagging_fraction': 0.7989705947017415}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:00,720] Trial 12 finished with value: 0.9049295774647887 and parameters: {'n_estimators': 353, 'max_depth': 66, 'learning_rate': 0.15773180380149104, 'subsample': 0.5256007255225678, 'colsample_bytree': 0.7984367463822196, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6715339988685632, 'bagging_fraction': 0.7632045766922427}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:01,247] Trial 13 finished with value: 0.8669014084507043 and parameters: {'n_estimators': 352, 'max_depth': 67, 'learning_rate': 0.15645243606206888, 'subsample': 0.5240513144519912, 'colsample_bytree': 0.7998987119278683, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6735275783019453, 'bagging_fraction': 0.762373548561516}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:01,810] Trial 14 finished with value: 0.8890748630553864 and parameters: {'n_estimators': 355, 'max_depth': 66, 'learning_rate': 0.15601718370637382, 'subsample': 0.5011189847755783, 'colsample_bytree': 0.7189638758888426, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6825219465146334, 'bagging_fraction': 0.7246000896047353}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:02,357] Trial 15 finished with value: 0.9049295774647887 and parameters: {'n_estimators': 353, 'max_depth': 65, 'learning_rate': 0.16686330134690647, 'subsample': 0.5209553071078447, 'colsample_bytree': 0.7682108186621033, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6972902043960927, 'bagging_fraction': 0.7573588615144051}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:02,871] Trial 16 finished with value: 0.9049295774647887 and parameters: {'n_estimators': 351, 'max_depth': 67, 'learning_rate': 0.15998292174153977, 'subsample': 0.5267326011049518, 'colsample_bytree': 0.79968632744841, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6645302511131462, 'bagging_fraction': 0.7625047719982379}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:03,431] Trial 17 finished with value: 0.8705873402312843 and parameters: {'n_estimators': 353, 'max_depth': 66, 'learning_rate': 0.1559101632828042, 'subsample': 0.5125621383958752, 'colsample_bytree': 0.777522038125499, 'min_child_samples': 6, 'num_leaves': 28, 'feature_fraction': 0.6822920995910019, 'bagging_fraction': 0.726917932490144}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:03,968] Trial 18 finished with value: 0.8968948891031823 and parameters: {'n_estimators': 350, 'max_depth': 66, 'learning_rate': 0.16581130509401684, 'subsample': 0.5966929571817482, 'colsample_bytree': 0.7195801384894179, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6322489267303125, 'bagging_fraction': 0.7816446305811203}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:04,520] Trial 19 finished with value: 0.8968948891031823 and parameters: {'n_estimators': 345, 'max_depth': 65, 'learning_rate': 0.15871463238368352, 'subsample': 0.5100721175937668, 'colsample_bytree': 0.7862414905337374, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6684096629961274, 'bagging_fraction': 0.7649046441774587}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:05,069] Trial 20 finished with value: 0.8890748630553864 and parameters: {'n_estimators': 354, 'max_depth': 66, 'learning_rate': 0.16117699718727044, 'subsample': 0.5333023986405888, 'colsample_bytree': 0.7568388593339507, 'min_child_samples': 6, 'num_leaves': 28, 'feature_fraction': 0.6896039855681897, 'bagging_fraction': 0.7896036445462032}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:05,451] Trial 21 finished with value: 0.8968948891031823 and parameters: {'n_estimators': 353, 'max_depth': 65, 'learning_rate': 0.16688970118253696, 'subsample': 0.519585515120698, 'colsample_bytree': 0.7654337835361971, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6985956341967181, 'bagging_fraction': 0.7555952026471343}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:05,810] Trial 22 finished with value: 0.8845605700712589 and parameters: {'n_estimators': 352, 'max_depth': 65, 'learning_rate': 0.16798962262697584, 'subsample': 0.550396607743388, 'colsample_bytree': 0.7886932447339892, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6737927423855138, 'bagging_fraction': 0.7393892452480301}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:06,161] Trial 23 finished with value: 0.8781485053037608 and parameters: {'n_estimators': 352, 'max_depth': 65, 'learning_rate': 0.1699782283237357, 'subsample': 0.5180721154440497, 'colsample_bytree': 0.7423780526584709, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6929511063359154, 'bagging_fraction': 0.7537909780183728}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:06,524] Trial 24 finished with value: 0.8859154929577465 and parameters: {'n_estimators': 355, 'max_depth': 65, 'learning_rate': 0.16491878212196828, 'subsample': 0.5288793303739283, 'colsample_bytree': 0.7740234665211129, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.674157929444527, 'bagging_fraction': 0.7662487220408875}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:06,891] Trial 25 finished with value: 0.8938990989560592 and parameters: {'n_estimators': 353, 'max_depth': 65, 'learning_rate': 0.1505750204068161, 'subsample': 0.5042866379579596, 'colsample_bytree': 0.7603809655966491, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6596363451876857, 'bagging_fraction': 0.7280565072219519}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:07,248] Trial 26 finished with value: 0.8968948891031823 and parameters: {'n_estimators': 354, 'max_depth': 65, 'learning_rate': 0.16676115477454684, 'subsample': 0.5424968186942295, 'colsample_bytree': 0.7432233941296187, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6782679768847523, 'bagging_fraction': 0.7123412378831551}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:07,613] Trial 27 finished with value: 0.852099817407182 and parameters: {'n_estimators': 350, 'max_depth': 66, 'learning_rate': 0.15752675287647216, 'subsample': 0.5203236544418254, 'colsample_bytree': 0.7921195539689716, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6896873205170263, 'bagging_fraction': 0.7699290100355172}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:07,977] Trial 28 finished with value: 0.8890748630553864 and parameters: {'n_estimators': 352, 'max_depth': 66, 'learning_rate': 0.16402020526625505, 'subsample': 0.5114279609755275, 'colsample_bytree': 0.7771390042814164, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6944156654705862, 'bagging_fraction': 0.7577614355618701}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:08,334] Trial 29 finished with value: 0.8781485053037608 and parameters: {'n_estimators': 354, 'max_depth': 67, 'learning_rate': 0.16168364777221636, 'subsample': 0.5301859466007971, 'colsample_bytree': 0.7812008042828469, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6865212094639128, 'bagging_fraction': 0.7403173545181305}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:08,706] Trial 30 finished with value: 0.8938990989560592 and parameters: {'n_estimators': 355, 'max_depth': 65, 'learning_rate': 0.164141481386133, 'subsample': 0.506930342492022, 'colsample_bytree': 0.7208378893199885, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6579264908259704, 'bagging_fraction': 0.7812778244827168}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:09,069] Trial 31 finished with value: 0.8669014084507043 and parameters: {'n_estimators': 351, 'max_depth': 67, 'learning_rate': 0.159848022445618, 'subsample': 0.5233610568054634, 'colsample_bytree': 0.7942064768752091, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.666019603552865, 'bagging_fraction': 0.7585350162066538}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:09,427] Trial 32 finished with value: 0.8825330325491461 and parameters: {'n_estimators': 353, 'max_depth': 67, 'learning_rate': 0.15925727434483894, 'subsample': 0.518185553100915, 'colsample_bytree': 0.7996164705416612, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6630038170160457, 'bagging_fraction': 0.7484020119920979}. Best is trial 9 with value: 0.9049295774647887.
[I 2025-01-16 03:53:09,804] Trial 33 finished with value: 0.9075623858794888 and parameters: {'n_estimators': 351, 'max_depth': 67, 'learning_rate': 0.15448267394296994, 'subsample': 0.5269511197379662, 'colsample_bytree': 0.7934155342976048, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6517143535337945, 'bagging_fraction': 0.7445226444631788}. Best is trial 33 with value: 0.9075623858794888.
[I 2025-01-16 03:53:10,170] Trial 34 finished with value: 0.8968948891031823 and parameters: {'n_estimators': 349, 'max_depth': 67, 'learning_rate': 0.15413950510040159, 'subsample': 0.5164464444220658, 'colsample_bytree': 0.7722715306974302, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6511126424811908, 'bagging_fraction': 0.7420019039086443}. Best is trial 33 with value: 0.9075623858794888.
[I 2025-01-16 03:53:10,507] Trial 35 finished with value: 0.8906882591093117 and parameters: {'n_estimators': 354, 'max_depth': 66, 'learning_rate': 0.15439653938952985, 'subsample': 0.5516592529837907, 'colsample_bytree': 0.7834347562730085, 'min_child_samples': 6, 'num_leaves': 28, 'feature_fraction': 0.6324683002991403, 'bagging_fraction': 0.7323673863395913}. Best is trial 33 with value: 0.9075623858794888.
[I 2025-01-16 03:53:10,869] Trial 36 finished with value: 0.8814589665653495 and parameters: {'n_estimators': 352, 'max_depth': 65, 'learning_rate': 0.16839240461487745, 'subsample': 0.5085315813892105, 'colsample_bytree': 0.7917259015507094, 'min_child_samples': 5, 'num_leaves': 27, 'feature_fraction': 0.6512023077814713, 'bagging_fraction': 0.7469622419885863}. Best is trial 33 with value: 0.9075623858794888.
[I 2025-01-16 03:53:11,209] Trial 37 finished with value: 0.8968948891031823 and parameters: {'n_estimators': 353, 'max_depth': 67, 'learning_rate': 0.1571434247432469, 'subsample': 0.5576262128736726, 'colsample_bytree': 0.7373633460442549, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6427610177148282, 'bagging_fraction': 0.7338566110643457}. Best is trial 33 with value: 0.9075623858794888.
[I 2025-01-16 03:53:11,563] Trial 38 finished with value: 0.8859154929577465 and parameters: {'n_estimators': 348, 'max_depth': 66, 'learning_rate': 0.15240452326371803, 'subsample': 0.5423798018417452, 'colsample_bytree': 0.7255512754521013, 'min_child_samples': 5, 'num_leaves': 27, 'feature_fraction': 0.6785724601245987, 'bagging_fraction': 0.7528858311459986}. Best is trial 33 with value: 0.9075623858794888.
[I 2025-01-16 03:53:11,922] Trial 39 finished with value: 0.8825330325491461 and parameters: {'n_estimators': 349, 'max_depth': 66, 'learning_rate': 0.16714451866660304, 'subsample': 0.5330073163929845, 'colsample_bytree': 0.750601090304113, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6557373439364261, 'bagging_fraction': 0.7905768229941271}. Best is trial 33 with value: 0.9075623858794888.
[I 2025-01-16 03:53:12,283] Trial 40 finished with value: 0.8890748630553864 and parameters: {'n_estimators': 351, 'max_depth': 65, 'learning_rate': 0.15806137334959217, 'subsample': 0.5149763913849076, 'colsample_bytree': 0.7615011923628036, 'min_child_samples': 6, 'num_leaves': 28, 'feature_fraction': 0.6699372637824895, 'bagging_fraction': 0.7194525392855827}. Best is trial 33 with value: 0.9075623858794888.
[I 2025-01-16 03:53:12,646] Trial 41 finished with value: 0.8669014084507043 and parameters: {'n_estimators': 351, 'max_depth': 67, 'learning_rate': 0.15520117590690957, 'subsample': 0.5289157639104657, 'colsample_bytree': 0.7959415584742572, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6618784718271721, 'bagging_fraction': 0.7687153006440529}. Best is trial 33 with value: 0.9075623858794888.
[I 2025-01-16 03:53:13,014] Trial 42 finished with value: 0.8781485053037608 and parameters: {'n_estimators': 350, 'max_depth': 67, 'learning_rate': 0.1624640061538239, 'subsample': 0.524519485288776, 'colsample_bytree': 0.7957022082517862, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6456653847142939, 'bagging_fraction': 0.776416277960104}. Best is trial 33 with value: 0.9075623858794888.
[I 2025-01-16 03:53:13,387] Trial 43 finished with value: 0.8890748630553864 and parameters: {'n_estimators': 352, 'max_depth': 67, 'learning_rate': 0.16053814402597227, 'subsample': 0.5380173523130327, 'colsample_bytree': 0.7893441348085607, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6533910470070556, 'bagging_fraction': 0.7625605736316344}. Best is trial 33 with value: 0.9075623858794888.
[I 2025-01-16 03:53:13,758] Trial 44 finished with value: 0.8859154929577465 and parameters: {'n_estimators': 353, 'max_depth': 67, 'learning_rate': 0.1509871139472913, 'subsample': 0.5251059776906604, 'colsample_bytree': 0.7450140909902201, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6694319627788885, 'bagging_fraction': 0.7448986026477559}. Best is trial 33 with value: 0.9075623858794888.
[I 2025-01-16 03:53:14,115] Trial 45 finished with value: 0.874608026038979 and parameters: {'n_estimators': 350, 'max_depth': 67, 'learning_rate': 0.16558360450695353, 'subsample': 0.5054943225393232, 'colsample_bytree': 0.7812676461073227, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6789885701018927, 'bagging_fraction': 0.7596281776400561}. Best is trial 33 with value: 0.9075623858794888.
[I 2025-01-16 03:53:14,457] Trial 46 finished with value: 0.8669014084507043 and parameters: {'n_estimators': 351, 'max_depth': 67, 'learning_rate': 0.15344712058247278, 'subsample': 0.5140338069543147, 'colsample_bytree': 0.7985358403913279, 'min_child_samples': 5, 'num_leaves': 27, 'feature_fraction': 0.6383427153229198, 'bagging_fraction': 0.7498810220865589}. Best is trial 33 with value: 0.9075623858794888.
[I 2025-01-16 03:53:14,831] Trial 47 finished with value: 0.8781485053037608 and parameters: {'n_estimators': 354, 'max_depth': 65, 'learning_rate': 0.15513930723971067, 'subsample': 0.5271457517385051, 'colsample_bytree': 0.7865978283652676, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6643037994933814, 'bagging_fraction': 0.7730418245960087}. Best is trial 33 with value: 0.9075623858794888.

Best parameters for LightGBM: {'n_estimators': 353, 'max_depth': 66, 'learning_rate': 0.16737399597260014, 'subsample': 0.5695120914593372, 'colsample_bytree': 0.7398636753685246, 'min_child_samples': 5, 'num_leaves': 28, 'feature_fraction': 0.6846680225456911, 'bagging_fraction': 0.7920492707864726}
Best Macro F1 Score for LightGBM: 0.9131901718731393

In [ ]:
# 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,shuffle=True)

# SMOTE 적용
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

def optimize_catboost(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 765, 775),
        'depth': trial.suggest_int('depth', 3, 5),
        'learning_rate': trial.suggest_float('learning_rate', 0.09, 0.1),
        'subsample': trial.suggest_float('subsample', 0.9, 1.0),
        'random_state': 42,  # 고정된 랜덤 시드
        'verbose': 0,  # 출력 제어
        #'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1, 10),
        'colsample_bylevel': trial.suggest_float('colsample_bylevel', 0.9, 1.0)
    }
    model = CatBoostClassifier(**params)
    model.fit(X_train_smote, y_train_smote)
    y_pred = model.predict(X_test)
    return f1_score(y_test, y_pred, average='macro')

study_cat = optuna.create_study(direction='maximize')
study_cat.optimize(optimize_catboost, n_trials=100)
print("Best parameters for CatBoost:", study_cat.best_params)
print("Best Macro F1 Score for CatBoost:", study_cat.best_value)

[I 2025-01-16 03:58:23,693] A new study created in memory with name: no-name-f69ee32f-8520-4994-81bb-ef88aaf351c2
[I 2025-01-16 03:58:25,988] Trial 0 finished with value: 0.8746435925867257 and parameters: {'iterations': 768, 'depth': 3, 'learning_rate': 0.0933848600933555, 'subsample': 0.904432810564826, 'colsample_bylevel': 0.933570482160207}. Best is trial 0 with value: 0.8746435925867257.
[I 2025-01-16 03:58:30,602] Trial 1 finished with value: 0.8825657101519171 and parameters: {'iterations': 768, 'depth': 5, 'learning_rate': 0.09891350063805138, 'subsample': 0.9067843824491937, 'colsample_bylevel': 0.9741165079895057}. Best is trial 1 with value: 0.8825657101519171.
[I 2025-01-16 03:58:35,661] Trial 2 finished with value: 0.8866123399301513 and parameters: {'iterations': 769, 'depth': 5, 'learning_rate': 0.0979418361994029, 'subsample': 0.9969832395970732, 'colsample_bylevel': 0.9500418351124723}. Best is trial 2 with value: 0.8866123399301513.
[I 2025-01-16 03:58:38,167] Trial 3 finished with value: 0.8767525434023384 and parameters: {'iterations': 768, 'depth': 4, 'learning_rate': 0.09844664736142157, 'subsample': 0.9313831112121184, 'colsample_bylevel': 0.9649262253019364}. Best is trial 2 with value: 0.8866123399301513.
[I 2025-01-16 03:58:41,435] Trial 4 finished with value: 0.8767525434023384 and parameters: {'iterations': 773, 'depth': 4, 'learning_rate': 0.095387577048112, 'subsample': 0.9680201049290914, 'colsample_bylevel': 0.9542281638327537}. Best is trial 2 with value: 0.8866123399301513.
[I 2025-01-16 03:58:42,739] Trial 5 finished with value: 0.8882904985588767 and parameters: {'iterations': 773, 'depth': 3, 'learning_rate': 0.09525847714291542, 'subsample': 0.9922056698996359, 'colsample_bylevel': 0.9592498467494741}. Best is trial 5 with value: 0.8882904985588767.
[I 2025-01-16 03:58:44,696] Trial 6 finished with value: 0.8866123399301513 and parameters: {'iterations': 771, 'depth': 3, 'learning_rate': 0.091517079871225, 'subsample': 0.9574121419577761, 'colsample_bylevel': 0.9434023343192413}. Best is trial 5 with value: 0.8882904985588767.
[I 2025-01-16 03:58:48,154] Trial 7 finished with value: 0.8785766288683441 and parameters: {'iterations': 771, 'depth': 5, 'learning_rate': 0.09633977220488481, 'subsample': 0.978421361210341, 'colsample_bylevel': 0.9062211414974666}. Best is trial 5 with value: 0.8882904985588767.
[I 2025-01-16 03:58:49,792] Trial 8 finished with value: 0.8764441842310695 and parameters: {'iterations': 768, 'depth': 5, 'learning_rate': 0.09675828599763457, 'subsample': 0.9808443940562146, 'colsample_bylevel': 0.9710126431824075}. Best is trial 5 with value: 0.8882904985588767.
[I 2025-01-16 03:58:51,146] Trial 9 finished with value: 0.8923519009725907 and parameters: {'iterations': 770, 'depth': 4, 'learning_rate': 0.09010901355232097, 'subsample': 0.9406578180732541, 'colsample_bylevel': 0.9796245909657019}. Best is trial 9 with value: 0.8923519009725907.
[I 2025-01-16 03:58:52,531] Trial 10 finished with value: 0.8785766288683441 and parameters: {'iterations': 765, 'depth': 4, 'learning_rate': 0.0901557396597713, 'subsample': 0.9345477323391721, 'colsample_bylevel': 0.9980421116030502}. Best is trial 9 with value: 0.8923519009725907.
[I 2025-01-16 03:58:53,736] Trial 11 finished with value: 0.8785766288683441 and parameters: {'iterations': 775, 'depth': 3, 'learning_rate': 0.09364232958211244, 'subsample': 0.9397226399094973, 'colsample_bylevel': 0.9943155247603096}. Best is trial 9 with value: 0.8923519009725907.
[I 2025-01-16 03:58:54,931] Trial 12 finished with value: 0.870765148164529 and parameters: {'iterations': 773, 'depth': 3, 'learning_rate': 0.09394992378000272, 'subsample': 0.9490070396087681, 'colsample_bylevel': 0.9848663911492037}. Best is trial 9 with value: 0.8923519009725907.
[I 2025-01-16 03:58:56,275] Trial 13 finished with value: 0.8825657101519171 and parameters: {'iterations': 773, 'depth': 4, 'learning_rate': 0.09233987022720086, 'subsample': 0.9998214463451349, 'colsample_bylevel': 0.9316823450466585}. Best is trial 9 with value: 0.8923519009725907.
[I 2025-01-16 03:58:57,491] Trial 14 finished with value: 0.8866123399301513 and parameters: {'iterations': 775, 'depth': 3, 'learning_rate': 0.09516193141722619, 'subsample': 0.9209258769448474, 'colsample_bylevel': 0.9804837342880179}. Best is trial 9 with value: 0.8923519009725907.
[I 2025-01-16 03:59:00,164] Trial 15 finished with value: 0.8842863931569777 and parameters: {'iterations': 771, 'depth': 4, 'learning_rate': 0.09008434913812048, 'subsample': 0.9595888447793258, 'colsample_bylevel': 0.9612606045734181}. Best is trial 9 with value: 0.8923519009725907.
[I 2025-01-16 03:59:02,565] Trial 16 finished with value: 0.8825657101519171 and parameters: {'iterations': 765, 'depth': 3, 'learning_rate': 0.09166104991233599, 'subsample': 0.9815370083566652, 'colsample_bylevel': 0.920472723977166}. Best is trial 9 with value: 0.8923519009725907.
[I 2025-01-16 03:59:03,958] Trial 17 finished with value: 0.8848735263585252 and parameters: {'iterations': 770, 'depth': 4, 'learning_rate': 0.096865560271507, 'subsample': 0.9471120721150224, 'colsample_bylevel': 0.9887304684336651}. Best is trial 9 with value: 0.8923519009725907.
[I 2025-01-16 03:59:05,165] Trial 18 finished with value: 0.8825657101519171 and parameters: {'iterations': 772, 'depth': 3, 'learning_rate': 0.09973968733142068, 'subsample': 0.9215377649923433, 'colsample_bylevel': 0.9759511991404848}. Best is trial 9 with value: 0.8923519009725907.
[I 2025-01-16 03:59:06,548] Trial 19 finished with value: 0.8807833537331702 and parameters: {'iterations': 774, 'depth': 4, 'learning_rate': 0.09265521597317321, 'subsample': 0.9680317493709344, 'colsample_bylevel': 0.9652220498159129}. Best is trial 9 with value: 0.8923519009725907.
[I 2025-01-16 03:59:08,199] Trial 20 finished with value: 0.8882904985588767 and parameters: {'iterations': 766, 'depth': 5, 'learning_rate': 0.09408343934296898, 'subsample': 0.9903616041171127, 'colsample_bylevel': 0.9419162737984228}. Best is trial 9 with value: 0.8923519009725907.
[I 2025-01-16 03:59:09,812] Trial 21 finished with value: 0.8882904985588767 and parameters: {'iterations': 766, 'depth': 5, 'learning_rate': 0.094368379642775, 'subsample': 0.9920275107085466, 'colsample_bylevel': 0.9349600978922484}. Best is trial 9 with value: 0.8923519009725907.
[I 2025-01-16 03:59:11,448] Trial 22 finished with value: 0.8964721364579643 and parameters: {'iterations': 766, 'depth': 5, 'learning_rate': 0.09584121659571211, 'subsample': 0.9719295371632166, 'colsample_bylevel': 0.9561117892926355}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:13,906] Trial 23 finished with value: 0.890718074255406 and parameters: {'iterations': 770, 'depth': 5, 'learning_rate': 0.09583625568520741, 'subsample': 0.9701486360865542, 'colsample_bylevel': 0.9567498022948456}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:17,580] Trial 24 finished with value: 0.8882904985588767 and parameters: {'iterations': 770, 'depth': 5, 'learning_rate': 0.09611998042578106, 'subsample': 0.9691593242372558, 'colsample_bylevel': 0.9516964872042498}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:19,213] Trial 25 finished with value: 0.8866123399301513 and parameters: {'iterations': 767, 'depth': 5, 'learning_rate': 0.09773973623203973, 'subsample': 0.956190662271756, 'colsample_bylevel': 0.9251265609150489}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:20,842] Trial 26 finished with value: 0.870765148164529 and parameters: {'iterations': 769, 'depth': 5, 'learning_rate': 0.09590061525360087, 'subsample': 0.9740472092627842, 'colsample_bylevel': 0.967596542170059}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:22,211] Trial 27 finished with value: 0.8866123399301513 and parameters: {'iterations': 769, 'depth': 4, 'learning_rate': 0.09487493228760835, 'subsample': 0.9408918896963072, 'colsample_bylevel': 0.9436173791398725}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:23,847] Trial 28 finished with value: 0.8866123399301513 and parameters: {'iterations': 767, 'depth': 5, 'learning_rate': 0.09724406642650427, 'subsample': 0.9609030944394961, 'colsample_bylevel': 0.9566506746179484}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:25,216] Trial 29 finished with value: 0.8807833537331702 and parameters: {'iterations': 767, 'depth': 4, 'learning_rate': 0.0930502610353588, 'subsample': 0.9851461869006439, 'colsample_bylevel': 0.9893538571617476}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:26,950] Trial 30 finished with value: 0.8785766288683441 and parameters: {'iterations': 772, 'depth': 5, 'learning_rate': 0.0909956337102791, 'subsample': 0.9533011096631935, 'colsample_bylevel': 0.9783997904986803}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:29,082] Trial 31 finished with value: 0.8803381001523416 and parameters: {'iterations': 770, 'depth': 3, 'learning_rate': 0.09551078112778043, 'subsample': 0.9895220450161335, 'colsample_bylevel': 0.9607618855041349}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:32,136] Trial 32 finished with value: 0.8807833537331702 and parameters: {'iterations': 772, 'depth': 4, 'learning_rate': 0.09437347962858834, 'subsample': 0.9729650286652596, 'colsample_bylevel': 0.9580858659182155}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:33,809] Trial 33 finished with value: 0.8803381001523416 and parameters: {'iterations': 769, 'depth': 5, 'learning_rate': 0.09475640313932863, 'subsample': 0.9624590872314526, 'colsample_bylevel': 0.9698003245924748}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:35,475] Trial 34 finished with value: 0.8785766288683441 and parameters: {'iterations': 774, 'depth': 5, 'learning_rate': 0.09604686415871254, 'subsample': 0.903781783069618, 'colsample_bylevel': 0.950129054242384}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:37,104] Trial 35 finished with value: 0.8825657101519171 and parameters: {'iterations': 771, 'depth': 5, 'learning_rate': 0.09763128294232429, 'subsample': 0.9209303470606871, 'colsample_bylevel': 0.9471104596942025}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:38,486] Trial 36 finished with value: 0.8825657101519171 and parameters: {'iterations': 770, 'depth': 4, 'learning_rate': 0.0955976125828936, 'subsample': 0.9459574601117267, 'colsample_bylevel': 0.9353757211143456}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:39,685] Trial 37 finished with value: 0.8842863931569777 and parameters: {'iterations': 768, 'depth': 3, 'learning_rate': 0.09840587099978038, 'subsample': 0.9951901422703182, 'colsample_bylevel': 0.9733344435798525}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:41,058] Trial 38 finished with value: 0.8767525434023384 and parameters: {'iterations': 766, 'depth': 4, 'learning_rate': 0.09660845328642328, 'subsample': 0.9656424680917904, 'colsample_bylevel': 0.9636250673473088}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:43,237] Trial 39 finished with value: 0.8727795193312435 and parameters: {'iterations': 774, 'depth': 5, 'learning_rate': 0.09484725610392426, 'subsample': 0.9277453432509327, 'colsample_bylevel': 0.9561550093366663}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:46,272] Trial 40 finished with value: 0.8866123399301513 and parameters: {'iterations': 772, 'depth': 4, 'learning_rate': 0.09327469379495791, 'subsample': 0.9761637285358279, 'colsample_bylevel': 0.9001428854195133}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:48,279] Trial 41 finished with value: 0.8825657101519171 and parameters: {'iterations': 766, 'depth': 5, 'learning_rate': 0.09420667763379532, 'subsample': 0.9858008821031622, 'colsample_bylevel': 0.9449101189201953}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:49,931] Trial 42 finished with value: 0.8803381001523416 and parameters: {'iterations': 768, 'depth': 5, 'learning_rate': 0.0909064319167188, 'subsample': 0.9904110777171156, 'colsample_bylevel': 0.9397100473362612}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:51,553] Trial 43 finished with value: 0.8882904985588767 and parameters: {'iterations': 765, 'depth': 5, 'learning_rate': 0.09703046156121704, 'subsample': 0.9843668526526713, 'colsample_bylevel': 0.9538559504363293}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:53,172] Trial 44 finished with value: 0.8785766288683441 and parameters: {'iterations': 766, 'depth': 5, 'learning_rate': 0.09362497803081482, 'subsample': 0.9963452749174089, 'colsample_bylevel': 0.9404242694066952}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:54,782] Trial 45 finished with value: 0.8785766288683441 and parameters: {'iterations': 767, 'depth': 5, 'learning_rate': 0.09640081901585028, 'subsample': 0.9798590196283501, 'colsample_bylevel': 0.9303980542658999}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:56,012] Trial 46 finished with value: 0.8842863931569777 and parameters: {'iterations': 769, 'depth': 3, 'learning_rate': 0.09193181903239417, 'subsample': 0.938049511337921, 'colsample_bylevel': 0.9193551036198814}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 03:59:58,681] Trial 47 finished with value: 0.870765148164529 and parameters: {'iterations': 771, 'depth': 5, 'learning_rate': 0.09531998141525926, 'subsample': 0.9715715637187118, 'colsample_bylevel': 0.9820166483620271}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:02,164] Trial 48 finished with value: 0.870765148164529 and parameters: {'iterations': 768, 'depth': 5, 'learning_rate': 0.09060889155819842, 'subsample': 0.953964271863918, 'colsample_bylevel': 0.9485823360923589}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:03,383] Trial 49 finished with value: 0.8866123399301513 and parameters: {'iterations': 773, 'depth': 3, 'learning_rate': 0.09922327327002728, 'subsample': 0.9144460932078936, 'colsample_bylevel': 0.9989738418633347}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:04,767] Trial 50 finished with value: 0.8825657101519171 and parameters: {'iterations': 765, 'depth': 4, 'learning_rate': 0.09571131881271618, 'subsample': 0.977961002179614, 'colsample_bylevel': 0.9622298059615931}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:06,420] Trial 51 finished with value: 0.890718074255406 and parameters: {'iterations': 766, 'depth': 5, 'learning_rate': 0.09437200649970941, 'subsample': 0.9917481823303473, 'colsample_bylevel': 0.9370730090136244}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:08,029] Trial 52 finished with value: 0.8842863931569777 and parameters: {'iterations': 766, 'depth': 5, 'learning_rate': 0.09396564869183636, 'subsample': 0.9986508820143782, 'colsample_bylevel': 0.9407335912835123}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:09,669] Trial 53 finished with value: 0.8842863931569777 and parameters: {'iterations': 767, 'depth': 5, 'learning_rate': 0.09513338203017474, 'subsample': 0.9884016642772193, 'colsample_bylevel': 0.9257604158050098}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:11,275] Trial 54 finished with value: 0.8825657101519171 and parameters: {'iterations': 765, 'depth': 5, 'learning_rate': 0.09261543797610342, 'subsample': 0.9918130778557642, 'colsample_bylevel': 0.937745912289983}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:14,613] Trial 55 finished with value: 0.8964721364579643 and parameters: {'iterations': 766, 'depth': 5, 'learning_rate': 0.09446796103775522, 'subsample': 0.9939360892675471, 'colsample_bylevel': 0.9512841748773474}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:17,093] Trial 56 finished with value: 0.8785766288683441 and parameters: {'iterations': 770, 'depth': 5, 'learning_rate': 0.09456303916796353, 'subsample': 0.9946304886508663, 'colsample_bylevel': 0.9521595123115385}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:18,290] Trial 57 finished with value: 0.8746435925867257 and parameters: {'iterations': 771, 'depth': 3, 'learning_rate': 0.09368261585893808, 'subsample': 0.9825365256594678, 'colsample_bylevel': 0.9671386384149046}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:19,643] Trial 58 finished with value: 0.8767525434023384 and parameters: {'iterations': 768, 'depth': 4, 'learning_rate': 0.0962939492767711, 'subsample': 0.999640983686096, 'colsample_bylevel': 0.9594526310311562}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:21,322] Trial 59 finished with value: 0.8842863931569777 and parameters: {'iterations': 775, 'depth': 5, 'learning_rate': 0.09727076739329056, 'subsample': 0.9289915617260467, 'colsample_bylevel': 0.9723131108946179}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:22,948] Trial 60 finished with value: 0.8825657101519171 and parameters: {'iterations': 767, 'depth': 5, 'learning_rate': 0.09579812635919381, 'subsample': 0.9415203352130274, 'colsample_bylevel': 0.9479664959068914}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:24,582] Trial 61 finished with value: 0.8882904985588767 and parameters: {'iterations': 766, 'depth': 5, 'learning_rate': 0.09515792293162917, 'subsample': 0.9939083290630566, 'colsample_bylevel': 0.9292299240687608}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:26,331] Trial 62 finished with value: 0.8825657101519171 and parameters: {'iterations': 766, 'depth': 5, 'learning_rate': 0.09413674977005394, 'subsample': 0.9868490087529251, 'colsample_bylevel': 0.9441435143126592}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:29,854] Trial 63 finished with value: 0.8785766288683441 and parameters: {'iterations': 765, 'depth': 5, 'learning_rate': 0.09295967993469732, 'subsample': 0.9817700507140324, 'colsample_bylevel': 0.955141037203055}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:32,227] Trial 64 finished with value: 0.8866123399301513 and parameters: {'iterations': 767, 'depth': 5, 'learning_rate': 0.0945394805161971, 'subsample': 0.9921178377970438, 'colsample_bylevel': 0.9521249881012793}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:33,883] Trial 65 finished with value: 0.8825657101519171 and parameters: {'iterations': 766, 'depth': 5, 'learning_rate': 0.09536067247825902, 'subsample': 0.9341644385183672, 'colsample_bylevel': 0.993706193047768}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:35,499] Trial 66 finished with value: 0.8807833537331702 and parameters: {'iterations': 765, 'depth': 5, 'learning_rate': 0.09379485978102431, 'subsample': 0.9639352515417079, 'colsample_bylevel': 0.9161131607875416}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:36,868] Trial 67 finished with value: 0.8866123399301513 and parameters: {'iterations': 769, 'depth': 4, 'learning_rate': 0.09477757798793818, 'subsample': 0.9753284092621224, 'colsample_bylevel': 0.9766688732970011}. Best is trial 22 with value: 0.8964721364579643.
[I 2025-01-16 04:00:38,507] Trial 68 finished with value: 0.8866123399301513 and parameters: {'iterations': 767, 'depth': 5, 'learning_rate': 0.09658523108525192, 'subsample': 0.9509363155129016, 'colsample_bylevel': 0.9461900569433334}. Best is trial 22 with value: 0.8964721364579643.

Best parameters for CatBoost: {'iterations': 770, 'depth': 3, 'learning_rate': 0.09545073710689564, 'subsample': 0.9956197806930602, 'colsample_bylevel': 0.9579137038910763}
Best Macro F1 Score for CatBoost: 0.9006527947776417

**K-FOLD 10 검증**

In [47]:
base_models = [
    ('xgb', XGBClassifier(
        eval_metric='logloss', random_state=42,
        n_estimators=832, max_depth=12, learning_rate=0.20593358762047578,
        subsample=0.5075069759848869, colsample_bytree=0.7424805892464985,
        min_child_weight=5.409454498304978, gamma=0.9114298633986331
    )),
    ('cat', CatBoostClassifier(
        verbose=0, random_state=42,
        iterations=770, depth=3, learning_rate=0.09545073710689564,
        subsample=0.9956197806930602, colsample_bylevel=0.9579137038910763
    )),
    ('lgb', LGBMClassifier(
        random_state=42,
        n_estimators=353, max_depth=66, learning_rate=0.16737399597260014,
        subsample=0.5695120914593372, colsample_bytree=0.7398636753685246,
        min_child_samples=5, num_leaves=28, feature_fraction=0.6846680225456911,
        bagging_fraction=0.7920492707864726, verbose=-1
    ))
]

voting_clf = VotingClassifier(estimators=base_models, voting='soft')

kf = KFold(n_splits=10, shuffle=True, random_state=SEED)

scores = {
    "macro_f1": [],
    "accuracy": [],
    "precision": [],
    "recall": []
}


for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    voting_clf.fit(X_train, y_train)

    y_pred = voting_clf.predict(X_test)

    scores["macro_f1"].append(f1_score(y_test, y_pred, average='macro'))
    scores["accuracy"].append(accuracy_score(y_test, y_pred))
    scores["precision"].append(precision_score(y_test, y_pred, average='macro'))
    scores["recall"].append(recall_score(y_test, y_pred, average='macro'))

print("Average Macro F1 Score:", np.mean(scores["macro_f1"]))
print("Average Accuracy:", np.mean(scores["accuracy"]))
print("Average Macro Precision:", np.mean(scores["precision"]))
print("Average Macro Recall:", np.mean(scores["recall"]))

Average Macro F1 Score: 0.9196654091730876
Average Accuracy: 0.9675554880928287
Average Macro Precision: 0.9428049119126026
Average Macro Recall: 0.9031332897258721

**모델 훈련**

In [48]:
# 베이스 모델
base_models = [
    ('xgb', XGBClassifier(
        eval_metric='logloss', random_state=42,
        n_estimators=832, max_depth=12, learning_rate=0.20593358762047578,
        subsample=0.5075069759848869, colsample_bytree=0.7424805892464985,
        min_child_weight=5.409454498304978, gamma=0.9114298633986331
    )),
    ('cat', CatBoostClassifier(
        verbose=0, random_state=42,
        iterations=770, depth=3, learning_rate=0.09545073710689564,
        subsample=0.9956197806930602, colsample_bylevel=0.9579137038910763
    )),
    ('lgb', LGBMClassifier(
        random_state=42,
        n_estimators=353, max_depth=66, learning_rate=0.16737399597260014,
        subsample=0.5695120914593372, colsample_bytree=0.7398636753685246,
        min_child_samples=5, num_leaves=28, feature_fraction=0.6846680225456911,
        bagging_fraction=0.7920492707864726, verbose=-1
    ))
]

voting_clf = VotingClassifier(estimators=base_models, voting='soft')

    # 보팅 모델 학습
voting_clf.fit(X, y)

VotingClassifier(estimators=[('xgb',
                              XGBClassifier(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=0.7424805892464985,
                                            device=None,
                                            early_stopping_rounds=None,
                                            enable_categorical=False,
                                            eval_metric='logloss',
                                            feature_types=None,
                                            gamma=0.9114298633986331,
                                            grow_policy=None,
                                            importance_type=None,
                                            interac...
                              <catboost.core.CatBoostClassifier object at 0x7f36811e1950>),
                             ('lgb',
                              LGBMClassifier(bagging_fraction=0.7920492707864726,
                                             colsample_bytree=0.7398636753685246,
                                             feature_fraction=0.6846680225456911,
                                             learning_rate=0.16737399597260014,
                                             max_depth=66, min_child_samples=5,
                                             n_estimators=353, num_leaves=28,
                                             random_state=42,
                                             subsample=0.5695120914593372,
                                             verbose=-1))],
                 voting='soft')

**제출**

In [54]:
test1 = test

In [55]:
pred = pd.Series(voting_clf.predict(test1))

In [56]:
submit = pd.read_csv('./sample_submission.csv')

In [57]:
submit['허위매물여부'] = pred
submit.head()
submit.to_csv('./final_submission.csv',index=False)